version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_NAME=nutri_tracker_db
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_password